### ISSUE TITLE
musl issues

### ISSUE THREAD

**Issue by lucize** [bvanassche/scst#23]
how about  ?
`warning: #warning redirecting incorrect #include <sys/poll.h> to <poll.h> [-Wcpp]`

and

```
stpgd_main.c:75:3: warning: incompatible implicit declaration of built-in function 'fprintf'
stpgd_main.c:75:3: note: include '<stdio.h>' or provide a declaration of 'fprintf'
stpgd_main.c:24:1:
+#include <stdio.h>

stpgd_main.c:75:11: error: 'stderr' undeclared (first use in this function)
   fprintf(stderr, "Try '%s --help' for more information.\n", app_name);
           ^~~~~~

```

```
--- a/usr/stpgd/stpgd_main.c 
+++ b/usr/stpgd/stpgd_main.c
@@ -17,6 +17,7 @@
 #include <syslog.h>
 #include <signal.h>
 #include <syslog.h>
+#include <stdio.h>

 #include "version.h"
 #include "debug.h"

```

**Comment by bvanassche** [comment]
On which Linux distribution was this encountered and which version of that distribution?

**Comment by lucize** [comment]
I'm trying to port it to openwrt (crosscompile with musl) scst-3.4.0
gcc-8.4.0, linux-5.4.42, musl-1.1.24, binutils-2.31.1

managed to compile it, didn't tested yet, can this be used only with sysfs ? adding perl as a dependency would add unneeded space usage  

there are also some warings like this

```
scst-3.4.0/qla2x00t/qla_nx.c: In function 'qla82xx_pci_set_window':
scst-3.4.0/qla2x00t/qla_nx.h:483:28: warning: conversion from 'long long unsigned int' to 'uintptr_t' {aka 'long unsigned int'} changes value from '8589934592' to '0' [-Woverflow]
 #define QLA82XX_ADDR_OCM0  (0x0000000200000000ULL)
                            ^~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by bvanassche** [comment]
Thank you for having reported this. The following changes have been committed on the git master branch and also on the Subversion trunk:
* #include <sys/poll.h> has been changed into #include <poll.h>.
* #include <stdio.h> has been added in the stpgd_main.c source file.
* SCST should again build cleanly against a 32-bit kernel.
* I am not sure whether the qla2x00t driver and the qla2x00t-32gbit driver are useful on OpenWrt. Both drivers implement support for QLogic PCIe interface adapters. Do any of the devices supported by OpenWrt that have PCIe slots?
* scstadmin is popular among SCST users but installing it is optional. SCST provides a sysfs interface (/sys/kernel/scst_tgt/...) and the SCST sysfs hierarchy is configurable without scstadmin. However, some software will be required to save and restore SCST configuration information.

**Comment by lucize** [comment]
don't know if you noticed about
```
message.c: In function 'iscsi_adm_request_listen':
message.c:38:2: warning: implicit declaration of function 'memset' [-Wimplicit-function-declaration]
  memset(&addr, 0, sizeof(addr));
  ^~~~~~
message.c:38:2: warning: incompatible implicit declaration of built-in function 'memset'
message.c:38:2: note: include '<string.h>' or provide a declaration of 'memset'
message.c:28:1:
+#include <string.h>
```
as I edited the previous comment
and how about  ?

```
In file included from crc32.c:4:
common.h:64:2: error: unknown type name 'loff_t'
  loff_t file_size; /* in bytes */
  ^~~~~~

```
this one was fixed by adding TARGET_CFLAGS += -Dloff_t=off_t

what is the policy of the new releases ?
is time based or importance related ?

**Comment by bvanassche** [comment]
A new version of SCST is released about once a year, usually in December.

The Subversion trunk and git master branches are kept in sync and can be considered as a "rolling release". Several users follow these branches and update periodically.

I'd like to fix the musl issues but I'm not sure what the best way is to build against musl. Are there instructions available for setting up an OpenWRT cross-compilation environment or should I perhaps download the musl source code and build SCST against the musl headers?

Does OpenWRT support a package manager? Are you familiar with the SCST "make rpm" and "make dpkg" build methods?

**Comment by bvanassche** [comment]
An update: I came across the Alpine Linux project, installed it in a VM and fixed the compiler warnings reported inside that VM. An additional fix has been checked in on the trunk and on the master branch.

**Comment by lucize** [comment]
you can use this https://openwrt.org/docs/guide-developer/quickstart-build-images, this way you can also test for arm targets, some are having sata connectivity
you can find my WIP recipe for scsc https://gist.github.com/lucize/edb9ec682d9e24ffe414a6076f9da93a
you add the Makefile in ex: feeds/packages/net/scst and symlink the folder in package/feeds/packages
then make menuconfig, select it and build it
make prepare (V=s for more debug) (-j$(NUM_CPU) for nr_cpu parallel build)
then ex: make package/scst/compile V=s -j10
openwrt can also pick github latest commit via codeload but usually the project picks up only the releases and adds as patches the new commits but in this case there are a lot of them after the latest tag

**Comment by bvanassche** [comment]
Would it help if I would release a new version from the master branch after you have had the chance whether the master branch builds and works fine in OpenWRT?

**Comment by lucize** [comment]
yes, I'll also run test it

**Comment by lucize** [comment]
so with latest I have this error, not seen in 3.4

```
[  276.507429] [2813]: scst: ***ERROR***: PR file name /var/lib/scst/pr/0:0:0:0 parent directory doesn't exist
[  276.537349] [2825]: scst: User interface thread started
[  276.554175] [2813]: scst: ***ERROR***: PR file name /var/lib/scst/pr/6:0:0:0 parent directory doesn't exist
[  276.584310] [2851]: scst: Init thread started
[  276.597846] [2852]: scst: Task management thread started
[  276.614153] [2813]: scst: Target template copy_manager registered successfully
[  276.636267] [2813]: scst: Target copy_manager_tgt for template copy_manager registered successfully
[  276.663821] [2813]: scst: Using security group "copy_manager_tgt" for initiator "copy_manager_sess" (target copy_manager_tgt)
[  276.698336] [2813]: scst: SCST version 3.5.0-pre loaded successfully (global max mem for commands ignored, per device 77MB)
[  276.732190] [2813]: scst: Enabled features: TRACING
[  276.747338] [2853]: scst: Management thread started

```

**Comment by lucize** [comment]
so it's working with scst_vdisk but with scst_disk I'm flooded with lots of errors and can't do anything on the machine, had to take a picture as it was scrolling too fast:

```
Command finished with CHECK CONDITION, but without sense data (opcode MODE SENSE(6)), issuing REQUEST SENSE
***ERROR***: Unable to issue REQUEST SENSE, returning HARDWARE ERROR
```
```
mkdir -p /var/lib/scst/pr/
modprobe scst_disk
modprobe scst_vdisk
modprobe iscsi-scst
iscsi-scstd
```
`echo "add_device dev1 filename=/dev/dev1" >/sys/kernel/scst_tgt/handlers/vdisk_blockio/mgmt`

or

`echo "add_device 0:0:0:0" >/sys/kernel/scst_tgt/handlers/dev_disk/mgmt`

`echo "add_target iqn.2007-05.com.example:storage.iscsi-scst-1" > /sys/kernel/scst_tgt/targets/iscsi/mgmt`

`echo "add 0:0:0:0 0" > /sys/kernel/scst_tgt/targets/iscsi/iqn.2007-05.com.example\:storage.iscsi-scst-1/luns/mgmt`
or
`echo "add dev1 0" > /sys/kernel/scst_tgt/targets/iscsi/iqn.2007-05.com.example\:storage.iscsi-scst-1/luns/mgmt
`
```

echo 1 >/sys/kernel/scst_tgt/targets/iscsi/iqn.2007-05.com.example\:storage.iscsi-scst-1/enabled
echo 1 >/sys/kernel/scst_tgt/targets/iscsi/enabled

```

**Comment by bvanassche** [comment]
The /var/lib/scst/... directories should be created automatically when running "make install", "rpm -i ..." or "dpkg -i ...".

Does 0:0:0:0 correspond to the USB or to the SATA disk? I have not yet tried to configure SCST to talk to an USB disk. Although this should work in theory, some USB disks have buggy controllers.

**Comment by lucize** [comment]
> /var/lib/scst/... directories

ok so is a runtime dependency, /var in openwrt case is a tmpfs so I'll create them before modprobe

there should be some files in that folder  ? as I have nothing there

> Does 0:0:0:0 correspond to the USB or to the SATA disk?

it's the sata disk, the default kernel on 32 bit has hugemem activated, I saw some warnings, could this be a problem ?

**Comment by bvanassche** [comment]
That's an interesting observation. Is there any information in the kernel log (dmesg output) that can help to figure out what is going on, e.g. a `Call Trace`?

**Comment by lucize** [comment]
can't do anything on the system once the error starts, I'll try on an x64 build and on an arm (mvebu)

**Comment by lucize** [comment]
@bvanassche 
I wanted to make a build for target-arm_cortex-a9+vfpv3-d16_musl_eabi and I get the attached error
[scst_mvebu_arm_cortex-a9.txt](https://github.com/bvanassche/scst/files/4753602/scst_mvebu_arm_cortex-a9.txt)

**Comment by lucize** [comment]
so I tested on a multicore cpu and it seems I could get some more output from dmesg and a picture
[scst_disk_err.txt](https://github.com/bvanassche/scst/files/4754067/scst_disk_err.txt)
![IMG_20200609_211620](https://user-images.githubusercontent.com/6313831/84185634-fc6ce500-aa97-11ea-8cf9-d7330e19d436.jpg)

**Comment by bvanassche** [comment]
A fix to make SCST build on ARM CPU's has been checked in.

Thank you for having shared more information about the earlier reported crash. I'm still working on analyzing that information.

**Comment by lucize** [comment]
I've got a more complete trace
[scst_disk_err.txt](https://github.com/bvanassche/scst/files/4757393/scst_disk_err.txt)


the arm is working just that at compile  there are lots of warnings like -Wsign-compare

```
 warning: comparison of integer expressions of different signedness: 'unsigned int' and 'int' [-Wsign-compare]
  return refcount_read(&sk->sk_wmem_alloc) < (READ_ONCE(sk->sk_sndbuf) >> 1);
warning: comparison of integer expressions of different signedness: 'int' and 'u32' {aka 'const unsigned int'} [-Wsign-compare]
  return inet_csk_reqsk_queue_len(sk) >= sk->sk_max_ack_backlog;

```

**Comment by bvanassche** [comment]
Neither the Linux kernel nor the SCST project enable -Wsign-compare. I'm surprised that warnings about sign differences appear ...

**Comment by bvanassche** [comment]
Several cross-compilaton fixes have been checked in on the master branch and instructions for cross-compilation are available at https://github.com/bvanassche/scst/blob/master/README.cross-compilation . Further feedback is welcome.

**Comment by bvanassche** [comment]
A fix for removal of device handlers has been checked in as commit c5ff6adeaec6b330bae5d6fb99531ba200d2f79f. Please reopen this ticket if it needs further attention.

**Comment by lucize** [comment]
hi, sorry for late reply
it seems that it help a bit, this time kernel didn't crash

```
[  667.670528] [2381]: scst: ***ERROR***: Unable to issue REQUEST SENSE, returning HARDWARE ERROR
[  667.671288] [2381]: scst: Command finished with CHECK CONDITION, but without sense data (opcode PREVENT ALLOW MEDIUM REMOVAL), issuing REQUEST SENSE
[...]
[  866.065958] [1309]: scst: cmd 000000007f806f88 (tag 0, sn 0) being executed/xmitted (state PARSE, op REQUEST SENSE, proc time 173 sec., timeout 30 sec.), deferring ABORT (cmd_done_wait_count 0, cmd_finish_wait_count 30795, internal 1, mcmd fn 6 (mcmd 00000000a3634c4a),
[  866.135057] [1309]: scst: TM fn 4 (mcmd 000000003b2c79ff) finished, status 0
[  866.135698] [1309]: iscsi-scst: iSCSI TM fn 5 finished, status 0, dropped 0
[  866.136391] [1309]: scst: TM fn 6 (mcmd 000000000dcaf15c) finished, status 0
[  866.137020] [2748]: scst: Aborted cmd 00000000a830523c finished (tag 788529152, ref 1)
[  866.137722] [1309]: scst: Resetting LUN 0 (mcmd 0000000055441acd)
[  866.160748] [1309]: scst: Resetting host 0 bus
[  866.161199] [1309]: scst: scsi_reset_provider(0:0:0:0) returned 8195
[  866.161772] [1309]: scst: TM fn 4 (mcmd 0000000055441acd) finished, status 0
[  866.162397] [1309]: iscsi-scst: iSCSI TM fn 5 finished, status 0, dropped 0
[  866.163137] [1309]: scst: TM fn 6 (mcmd 00000000e79340fc) finished, status 0
[  866.163770] [2806]: scst: Aborted cmd 00000000663a2215 finished (tag 805306368, ref 1)
[  866.164472] [1309]: scst: Resetting LUN 0 (mcmd 000000008645728b)
[  866.187500] [1309]: scst: Resetting host 0 bus
[  866.187946] [1309]: scst: scsi_reset_provider(0:0:0:0) returned 8195
[  866.188516] [1309]: scst: TM fn 4 (mcmd 000000008645728b) finished, status 0
[  866.189140] [1309]: iscsi-scst: iSCSI TM fn 5 finished, status 0, dropped 0
[  866.339093] [2805]: iscsi-scst: Freeing conn 00000000479cde5a (sess=0000000083aae5a7, 0x4000037010040 1, initiator iqn.1991-05.com.microsoft:x260)
[  866.340365] [2805]: iscsi-scst: Freeing session 0000000083aae5a7 (SID 4000037010040)
[  867.042999] [2747]: iscsi-scst: Freeing conn 000000004337134e (sess=00000000956566a5, 0x3000037010040 1, initiator iqn.1991-05.com.microsoft:x260)
[  867.044265] [2747]: iscsi-scst: Freeing session 00000000956566a5 (SID 3000037010040)
[  874.785723] [1379]: iscsi-scst: iSCSI TM fn 5
[  874.786175] [1379]: scst: TM fn LUN_RESET/4 (mcmd 00000000622b979b, initiator iqn.1991-05.com.microsoft:x260, target iqn.2007-05.com.example:storage.iscsi-scst-1)
[  874.787635] [1309]: scst: Resetting LUN 0 (mcmd 00000000622b979b)
[  874.829320] [1309]: scst: cmd 00000000663a2215 (tag 838860800, sn 26) being executed/xmitted (state EXEC_CHECK_BLOCKING, op INQUIRY, proc time 8 sec., timeout 10 sec.), deferring ABORT (cmd_done_wait_count 0, cmd_finish_wait_count 1, internal 0, mcmd fn 4 (mcmd 00000000622b979b), initiator iqn.1991-05.com.microsoft:x260, target iqn.2007-05.com.example:storage.iscsi-scst-1)
[  874.832375] [1309]: scst: Resetting host 0 bus
[  874.832879] [1309]: scst: scsi_reset_provider(0:0:0:0) returned 8195
[  874.833490] [2806]: scst: Aborted cmd 00000000663a2215 finished (tag 838860800, ref 2)
[  874.834203] [1309]: scst: TM fn 4 (mcmd 00000000622b979b) finished, status 0
[  874.834828] [1309]: iscsi-scst: iSCSI TM fn 5 finished, status 0, dropped 0
[  884.784936] [1379]: iscsi-scst: iSCSI TM fn 5
[  884.785390] [1379]: scst: TM fn LUN_RESET/4 (mcmd 00000000b6950338, initiator iqn.1991-05.com.microsoft:x260, target iqn.2007-05.com.example:storage.iscsi-scst-1)
[  884.786842] [1309]: scst: Resetting LUN 0 (mcmd 00000000b6950338)
[  884.828804] [1309]: scst: cmd 00000000663a2215 (tag 872415232, sn 27) being executed/xmitted (state EXEC_CHECK_BLOCKING, op INQUIRY, proc time 9 sec., timeout 10 sec.), deferring ABORT (cmd_done_wait_count 0, cmd_finish_wait_count 1, internal 0, mcmd fn 4 (mcmd 00000000b6950338), initiator iqn.1991-05.com.microsoft:x260, target iqn.2007-05.com.example:storage.iscsi-scst-1)
[  884.831832] [1309]: scst: Resetting host 0 bus
[  884.832317] [1309]: scst: scsi_reset_provider(0:0:0:0) returned 8195
[  884.832997] [2806]: scst: Aborted cmd 00000000663a2215 finished (tag 872415232, ref 2)
[  884.833743] [1309]: scst: TM fn 4 (mcmd 00000000b6950338) finished, status 0
[  884.834386] [1309]: iscsi-scst: iSCSI TM fn 5 finished, status 0, dropped 0
[  894.785273] [1379]: iscsi-scst: iSCSI TM fn 5
[  894.785727] [1379]: scst: TM fn LUN_RESET/4 (mcmd 000000008b8aaffe, initiator iqn.1991-05.com.microsoft:x260, target iqn.2007-05.com.example:storage.iscsi-scst-1)
[  894.787177] [1309]: scst: Resetting LUN 0 (mcmd 000000008b8aaffe)
[  894.829129] [1309]: scst: cmd 00000000f73f3788 (tag 905969664, sn 28) being executed/xmitted (state EXEC_CHECK_BLOCKING, op INQUIRY, proc time 9 sec., timeout 10 sec.), deferring ABORT (cmd_done_wait_count 0, cmd_finish_wait_count 1, internal 0, mcmd fn 4 (mcmd 000000008b8aaffe), initiator iqn.1991-05.com.microsoft:x260, target iqn.2007-05.com.example:storage.iscsi-scst-1)
[  894.832162] [1309]: scst: Resetting host 0 bus
[  894.832647] [1309]: scst: scsi_reset_provider(0:0:0:0) returned 8195
[  894.833329] [2806]: scst: Aborted cmd 00000000f73f3788 finished (tag 905969664, ref 2)
[  894.834074] [1309]: scst: TM fn 4 (mcmd 000000008b8aaffe) finished, status 0
[  894.834715] [1309]: iscsi-scst: iSCSI TM fn 5 finished, status 0, dropped 0
[  904.861072] [0]: iscsi-scst: ***ERROR***: Connection 000000005300ef54 with initiator iqn.1991-05.com.microsoft:x260 unexpectedly closed!
[  904.862778] [2936]: scst: TM fn NEXUS_LOSS_SESS/6 (mcmd 00000000b6335b82, initiator iqn.1991-05.com.microsoft:x260, target iqn.2007-05.com.example:storage.iscsi-scst-1)
[  904.864271] [1309]: scst: cmd 00000000557e1d8f (tag 939524096, sn 29) being executed/xmitted (state EXEC_CHECK_BLOCKING, op REPORT LUNS, proc time 10 sec., timeout 10 sec.), deferring ABORT (cmd_done_wait_count 0, cmd_finish_wait_count 1, internal 0, mcmd fn 6 (mcmd 00000000b6335b82), initiator iqn.1991-05.com.microsoft:x260, target iqn.2007-05.com.example:storage.iscsi-scst-1)
[  904.867388] [2806]: scst: Aborted cmd 00000000557e1d8f finished (tag 939524096, ref 2)
[  904.868118] [1309]: scst: TM fn 6 (mcmd 00000000b6335b82) finished, status 0
[  904.869690] [1403]: scst: Using security group "iqn.2007-05.com.example:storage.iscsi-scst-1" for initiator "iqn.1991-05.com.microsoft:x260" (target iqn.2007-05.com.example:storage.iscsi-scst-1)
[  904.871603] [1403]: iscsi-scst: Session 00000000d9f21d6e created: target 00000000cc36773e, tid 1, sid 0x6000037010040, initiator iqn.1991-05.com.microsoft:x260
[  904.872923] [1403]: iscsi-scst: Negotiated parameters: InitialR2T No, ImmediateData Yes, MaxConnections 1, MaxRecvDataSegmentLength 1048576, MaxXmitDataSegmentLength 65536,
[  904.874297] [1403]: iscsi-scst:     MaxBurstLength 262144, FirstBurstLength 65536, DefaultTime2Wait 0, DefaultTime2Retain 0,
[  904.875304] [1403]: iscsi-scst:     MaxOutstandingR2T 16, DataPDUInOrder Yes, DataSequenceInOrder Yes, ErrorRecoveryLevel 0,
[  904.876353] [1403]: iscsi-scst:     HeaderDigest None, DataDigest None, OFMarker No, IFMarker No, OFMarkInt 2048, IFMarkInt 2048, RDMAExtensions No
[  904.877533] [1403]: iscsi-scst: Target parameters set for session 6000037010040: QueuedCommands 32, Response timeout 90, Nop-In interval 30, Nop-In timeout 30
[  904.878970] [1403]: iscsi-scst: Creating connection 0000000023d000c9 for sid 0x6000037010040, cid 1 (initiator iqn.1991-05.com.microsoft:x260)
[  905.892394] [2936]: iscsi-scst: Freeing conn 000000005300ef54 (sess=0000000045f4af6d, 0x5000037010040 1, initiator iqn.1991-05.com.microsoft:x260)
[  905.893675] [2936]: iscsi-scst: Freeing session 0000000045f4af6d (SID 5000037010040)
[  914.862880] [1379]: iscsi-scst: iSCSI TM fn 5
[  914.863331] [1379]: scst: TM fn LUN_RESET/4 (mcmd 0000000055441acd, initiator iqn.1991-05.com.microsoft:x260, target iqn.2007-05.com.example:storage.iscsi-scst-1)
[  914.864846] [1309]: scst: Resetting LUN 0 (mcmd 0000000055441acd)
[  914.924840] [1309]: scst: cmd 000000005bb87c85 (tag 889192448, sn 30) being executed/xmitted (state EXEC_CHECK_BLOCKING, op REPORT LUNS, proc time 10 sec., timeout 10 sec.), deferring ABORT (cmd_done_wait_count 0, cmd_finish_wait_count 1, internal 0, mcmd fn 4 (mcmd 0000000055441acd), initiator iqn.1991-05.com.microsoft:x260, target iqn.2007-05.com.example:storage.iscsi-scst-1)
[  914.927943] [1309]: scst: Resetting host 0 bus
[  914.928429] [1309]: scst: scsi_reset_provider(0:0:0:0) returned 8195
[  914.929102] [2937]: scst: Aborted cmd 000000005bb87c85 finished (tag 889192448, ref 2)
[  914.929900] [1309]: scst: TM fn 4 (mcmd 0000000055441acd) finished, status 0
[  914.930545] [1309]: iscsi-scst: iSCSI TM fn 5 finished, status 0, dropped 0
[  924.860326] [1379]: iscsi-scst: iSCSI TM fn 5
[  924.860751] [1379]: scst: TM fn LUN_RESET/4 (mcmd 00000000e1d66746, initiator iqn.1991-05.com.microsoft:x260, target iqn.2007-05.com.example:storage.iscsi-scst-1)

```


also an unrelated problem if ipv6 is disabled

```

iscsi-scst/kernel/conn.c: In function 'iscsi_get_target_ip':
./include/net/sock.h:358:37: error: 'struct sock_common' has no member named 'skc_v6_rcv_saddr'; did you mean 'skc_rcv_saddr'?
 #define sk_v6_rcv_saddr __sk_common.skc_v6_rcv_saddr
                                     ^~~~~~~~~~~~~~~~
iscsi-scst/kernel/conn.c:150:45: note: in expansion of macro 'sk_v6_rcv_saddr'
   pos = scnprintf(buf, size, "[%pI6]", &sk->sk_v6_rcv_saddr);
                                             ^~~~~~~~~~~~~~~

```

**Comment by bvanassche** [comment]
A candidate fix has been checked in (c22a2d11b1ef3038561cb569467a9345fbeaf08e). Please update and retest.

**Comment by lucize** [comment]
ipv6 is ok, I'll try a native build on a musl based distro, maybe something is not right in cross compile

**Comment by lucize** [comment]
so I made a native build with latest on alpine linux 5.4.43-1-lts, same errors on dev_disk driver and an usb drive, kernel crashed with out of memory 

```
[ 3615.381769] [27151]: scst_prepare_request_sense:5922:Adding REQUEST SENSE cmd 811feee9 to head of active cmd list
[ 3615.381774] [27151]: scst: scst_pre_dev_done:3262:***ERROR***: Unable to issue REQUEST SENSE, returning HARDWARE ERROR
[ 3615.381779] [27151]: scst_set_cmd_error_status:1803:cmd d3f469d8 already has status 2 set
[ 3615.381786] [27151]: scst: scst_check_auto_sense:3198:CHECK_CONDITION, but no sense: cmd->status=2, cmd->msg_status=0, cmd->host_status=0, cmd->driver_status=8 (cmd d3f469d8)
[ 3615.381792] [27151]: scst: scst_pre_dev_done:3255:Command finished with CHECK CONDITION, but without sense data (opcode PREVENT ALLOW MEDIUM REMOVAL), issuing REQUEST SENSE
```
