### ISSUE TITLE
Current trunk fails to build on Centos 8.2.2004

### ISSUE THREAD

**Issue by dodexahedron** [bvanassche/scst#25]
On Centos 8.2, with kernel 4.18.0-193.6.3.el8_2.x86_64, the build fails, complaining about symbol redefinition:

root# make 2perf
cd scst && make 2perf
make[1]: Entering directory '/root/scst-trunk/scst'
make[1]: Leaving directory '/root/scst-trunk/scst'

root# make scst iscsi scstadm usr
cd scst && make all
make[1]: Entering directory '/root/scst-trunk/scst'
cd src && make all
make[2]: Entering directory '/root/scst-trunk/scst/src'
make -C certs KDIR=/lib/modules/4.18.0-193.6.3.el8_2.x86_64/build
make[3]: Entering directory '/root/scst-trunk/scst/src/certs'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/root/scst-trunk/scst/src/certs'
make -C /lib/modules/4.18.0-193.6.3.el8_2.x86_64/build M=/root/scst-trunk/scst/src BUILD_DEV=m
make[3]: Entering directory '/usr/src/kernels/4.18.0-193.6.3.el8_2.x86_64'
  CC [M]  /root/scst-trunk/scst/src/dev_handlers/scst_cdrom.o
In file included from /root/scst-trunk/scst/src/dev_handlers/../../include/scst.h:64,
                 from /root/scst-trunk/scst/src/dev_handlers/scst_cdrom.c:31:
/root/scst-trunk/scst/src/dev_handlers/../../include/backport.h:895:20: error: redefinition of ‘lockdep_register_key’
 static inline void lockdep_register_key(struct lock_class_key *key)
                    ^~~~~~~~~~~~~~~~~~~~
In file included from ./include/linux/spinlock_types.h:18,
                 from ./include/linux/spinlock.h:83,
                 from ./include/linux/wait.h:9,
                 from ./include/linux/wait_bit.h:8,
                 from ./include/linux/fs.h:7,
                 from ./include/drm-backport/linux/fs.h:14,
                 from ./include/linux/cdrom.h:14,
                 from /root/scst-trunk/scst/src/dev_handlers/scst_cdrom.c:21:
./include/linux/lockdep.h:461:20: note: previous definition of ‘lockdep_register_key’ was here
 static inline void lockdep_register_key(struct lock_class_key *key)
                    ^~~~~~~~~~~~~~~~~~~~
In file included from /root/scst-trunk/scst/src/dev_handlers/../../include/scst.h:64,
                 from /root/scst-trunk/scst/src/dev_handlers/scst_cdrom.c:31:
/root/scst-trunk/scst/src/dev_handlers/../../include/backport.h:899:20: error: redefinition of ‘lockdep_unregister_key’
 static inline void lockdep_unregister_key(struct lock_class_key *key)
                    ^~~~~~~~~~~~~~~~~~~~~~
In file included from ./include/linux/spinlock_types.h:18,
                 from ./include/linux/spinlock.h:83,
                 from ./include/linux/wait.h:9,
                 from ./include/linux/wait_bit.h:8,
                 from ./include/linux/fs.h:7,
                 from ./include/drm-backport/linux/fs.h:14,
                 from ./include/linux/cdrom.h:14,
                 from /root/scst-trunk/scst/src/dev_handlers/scst_cdrom.c:21:
./include/linux/lockdep.h:465:20: note: previous definition of ‘lockdep_unregister_key’ was here
 static inline void lockdep_unregister_key(struct lock_class_key *key)
                    ^~~~~~~~~~~~~~~~~~~~~~
make[5]: *** [scripts/Makefile.build:319: /root/scst-trunk/scst/src/dev_handlers/scst_cdrom.o] Error 1
make[4]: *** [scripts/Makefile.build:553: /root/scst-trunk/scst/src/dev_handlers] Error 2
make[3]: *** [Makefile:1545: _module_/root/scst-trunk/scst/src] Error 2
make[3]: Leaving directory '/usr/src/kernels/4.18.0-193.6.3.el8_2.x86_64'
make[2]: *** [Makefile:118: all] Error 2
make[2]: Leaving directory '/root/scst-trunk/scst/src'
make[1]: *** [Makefile:36: all] Error 2
make[1]: Leaving directory '/root/scst-trunk/scst'
make: *** [Makefile:138: scst] Error 2

root# cat /etc/centos-release
CentOS Linux release 8.2.2004 (Core) 
root# uname -a
Linux xxxxxxxx 4.18.0-193.6.3.el8_2.x86_64 #1 SMP Wed Jun 10 11:09:32 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

I performed a fresh checkout from subversion, just in case something had been modified.
This used to build properly, and unfortunately I didn't think to check which revision the successful build was from.

Removing those two structs all together from backport.h allows the build to complete.

This commit broke it:
https://github.com/bvanassche/scst/commit/c1a340b484eab81a4b9a81d6007f690661b5e3da#diff-57b08c4776620ea62ca7c0f0df32edaf

Perhaps an additional check for CentOS/RHEL 8 is necessary, here, as well.

**Comment by bvanassche** [comment]
Thanks for having reported this. This has been fixed by commit de023fe1fe4c.
