### ISSUE TITLE
Build failure since a2ed73c287

### ISSUE THREAD

**Issue by kusumi** [bvanassche/scst#15]
This commit
```
commit a2ed73c2877ab9d8a64ff46dfcd65ae773b1f1ec
Author: Bart Van Assche <bvanassche@acm.org>
Date:   Sat Apr 13 22:57:18 2019 +0000

    scst/include/backport.h: Backport FC_PORTSPEED_64GBIT
```
which backported `FC_PORTSPEED_64GBIT` broke compilation on Ubuntu running 4.15 kernel with below error message.
```
./include/scsi/scsi_transport_fc.h:142:30: error: expected identifier before numeric constant
 #define FC_PORTSPEED_64GBIT  0x1000
                              ^
```
This is what Ubuntu has in scsi_transport_fc.h.
```
# uname -r
4.15.0-36-generic
# grep FC_PORTSPEED_64GBIT /usr/src/linux-headers-`uname -r`/include/scsi/scsi_transport_fc.h
#define FC_PORTSPEED_64GBIT             0x1000
```
Given `FC_PORTSPEED_64GBIT` first appeared in upstream 4.16 in commit cc019a5a3b58670efe765f19aec42e28c16d7aed("scsi: scsi_transport_fc: fix typos on 64/128 GBit define names"), it looks like Ubuntu has also backported it to their 4.15 based kernels.

**Comment by bvanassche** [comment]
Thanks for having reported this. A candidate fix has been checked in. Please retest.

**Comment by kusumi** [comment]
Confirmed fix.
