### ISSUE TITLE
error compiling << ‘struct ib_device’ has no member named ‘attrs’>> with github.com/tinuzz/scst-3.x-debian files

### ISSUE THREAD

**Issue by mailinglists35** [bvanassche/scst#7]
I have git cloned this as `scst`: https://github.com/bvanassche/scst.git
Then inside `scst` dir I have cloned this as `debian` https://github.com/tinuzz/scst-3.x-debian.git

Then from `scst` dir I ran `dpkg-buildpackage -b -uc -us` which produced these debs that I have installed:
`scst-dkms_3.1.0-0isaac2_amd64.deb`
`scstadmin_3.1.0-0isaac2_amd64.deb`
`scst-fileio-tgt_3.1.0-0isaac2_amd64.deb`
`iscsi-scst_3.1.0-0isaac2_amd64.deb`

However build fails with this build log:

```
root@linux:/usr/local/src/scst# dkms build scst/3.1.0.1

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area....
make KERNELRELEASE=4.4.0-62-generic..............(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.4.0-62-generic (x86_64)
Consult /var/lib/dkms/scst/3.1.0.1/build/make.log for more information.

root@linux:/usr/local/src/scst# cat /var/lib/dkms/scst/3.1.0.1/build/make.log
DKMS make.log for scst-3.1.0.1 for kernel 4.4.0-62-generic (x86_64)
Tue Feb  7 17:52:53 EET 2017
cd scst && make all
make[1]: Entering directory '/var/lib/dkms/scst/3.1.0.1/build/scst'
cd src && make all
make[2]: Entering directory '/var/lib/dkms/scst/3.1.0.1/build/scst/src'
make -C /lib/modules/4.4.0-62-generic/build SUBDIRS=/var/lib/dkms/scst/3.1.0.1/build/scst/src BUILD_DEV=m
make[3]: Entering directory '/usr/src/linux-headers-4.4.0-62-generic'
  LD      /var/lib/dkms/scst/3.1.0.1/build/scst/src/built-in.o
  CC [M]  /var/lib/dkms/scst/3.1.0.1/build/scst/src/scst_main.o
  CC [M]  /var/lib/dkms/scst/3.1.0.1/build/scst/src/scst_targ.o
  CC [M]  /var/lib/dkms/scst/3.1.0.1/build/scst/src/scst_lib.o
  CC [M]  /var/lib/dkms/scst/3.1.0.1/build/scst/src/scst_sysfs.o
  CC [M]  /var/lib/dkms/scst/3.1.0.1/build/scst/src/scst_mem.o
  CC [M]  /var/lib/dkms/scst/3.1.0.1/build/scst/src/scst_debug.o
  CC [M]  /var/lib/dkms/scst/3.1.0.1/build/scst/src/scst_pres.o
  CC [M]  /var/lib/dkms/scst/3.1.0.1/build/scst/src/scst_no_dlm.o
  CC [M]  /var/lib/dkms/scst/3.1.0.1/build/scst/src/scst_dlm.o
  CC [M]  /var/lib/dkms/scst/3.1.0.1/build/scst/src/scst_tg.o
  CC [M]  /var/lib/dkms/scst/3.1.0.1/build/scst/src/scst_event.o
  CC [M]  /var/lib/dkms/scst/3.1.0.1/build/scst/src/scst_copy_mgr.o
  LD [M]  /var/lib/dkms/scst/3.1.0.1/build/scst/src/scst.o
  LD      /var/lib/dkms/scst/3.1.0.1/build/scst/src/dev_handlers/built-in.o
  CC [M]  /var/lib/dkms/scst/3.1.0.1/build/scst/src/dev_handlers/scst_cdrom.o
  CC [M]  /var/lib/dkms/scst/3.1.0.1/build/scst/src/dev_handlers/scst_changer.o
  CC [M]  /var/lib/dkms/scst/3.1.0.1/build/scst/src/dev_handlers/scst_disk.o
  CC [M]  /var/lib/dkms/scst/3.1.0.1/build/scst/src/dev_handlers/scst_modisk.o
  CC [M]  /var/lib/dkms/scst/3.1.0.1/build/scst/src/dev_handlers/scst_tape.o
  CC [M]  /var/lib/dkms/scst/3.1.0.1/build/scst/src/dev_handlers/scst_vdisk.o
  CC [M]  /var/lib/dkms/scst/3.1.0.1/build/scst/src/dev_handlers/scst_raid.o
  CC [M]  /var/lib/dkms/scst/3.1.0.1/build/scst/src/dev_handlers/scst_processor.o
  CC [M]  /var/lib/dkms/scst/3.1.0.1/build/scst/src/dev_handlers/scst_user.o
  Building modules, stage 2.
  MODPOST 10 modules
  CC      /var/lib/dkms/scst/3.1.0.1/build/scst/src/dev_handlers/scst_cdrom.mod.o
  LD [M]  /var/lib/dkms/scst/3.1.0.1/build/scst/src/dev_handlers/scst_cdrom.ko
  CC      /var/lib/dkms/scst/3.1.0.1/build/scst/src/dev_handlers/scst_changer.mod.o
  LD [M]  /var/lib/dkms/scst/3.1.0.1/build/scst/src/dev_handlers/scst_changer.ko
  CC      /var/lib/dkms/scst/3.1.0.1/build/scst/src/dev_handlers/scst_disk.mod.o
  LD [M]  /var/lib/dkms/scst/3.1.0.1/build/scst/src/dev_handlers/scst_disk.ko
  CC      /var/lib/dkms/scst/3.1.0.1/build/scst/src/dev_handlers/scst_modisk.mod.o
  LD [M]  /var/lib/dkms/scst/3.1.0.1/build/scst/src/dev_handlers/scst_modisk.ko
  CC      /var/lib/dkms/scst/3.1.0.1/build/scst/src/dev_handlers/scst_processor.mod.o
  LD [M]  /var/lib/dkms/scst/3.1.0.1/build/scst/src/dev_handlers/scst_processor.ko
  CC      /var/lib/dkms/scst/3.1.0.1/build/scst/src/dev_handlers/scst_raid.mod.o
  LD [M]  /var/lib/dkms/scst/3.1.0.1/build/scst/src/dev_handlers/scst_raid.ko
  CC      /var/lib/dkms/scst/3.1.0.1/build/scst/src/dev_handlers/scst_tape.mod.o
  LD [M]  /var/lib/dkms/scst/3.1.0.1/build/scst/src/dev_handlers/scst_tape.ko
  CC      /var/lib/dkms/scst/3.1.0.1/build/scst/src/dev_handlers/scst_user.mod.o
  LD [M]  /var/lib/dkms/scst/3.1.0.1/build/scst/src/dev_handlers/scst_user.ko
  CC      /var/lib/dkms/scst/3.1.0.1/build/scst/src/dev_handlers/scst_vdisk.mod.o
  LD [M]  /var/lib/dkms/scst/3.1.0.1/build/scst/src/dev_handlers/scst_vdisk.ko
  CC      /var/lib/dkms/scst/3.1.0.1/build/scst/src/scst.mod.o
  LD [M]  /var/lib/dkms/scst/3.1.0.1/build/scst/src/scst.ko
make[3]: Leaving directory '/usr/src/linux-headers-4.4.0-62-generic'
make[2]: Leaving directory '/var/lib/dkms/scst/3.1.0.1/build/scst/src'
make[1]: Leaving directory '/var/lib/dkms/scst/3.1.0.1/build/scst'
cd iscsi-scst && make include/iscsi_scst_itf_ver.h && make mods
make[1]: Entering directory '/var/lib/dkms/scst/3.1.0.1/build/iscsi-scst'
make[1]: 'include/iscsi_scst_itf_ver.h' is up to date.
make[1]: Leaving directory '/var/lib/dkms/scst/3.1.0.1/build/iscsi-scst'
make[1]: Entering directory '/var/lib/dkms/scst/3.1.0.1/build/iscsi-scst'
cp /var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/../scst/src/Module.symvers kernel/
if true; then                              \
  cp /var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/../scst/src/Module.symvers kernel/isert-scst; \
fi
make -C /lib/modules/4.4.0-62-generic/build SCST_INC_DIR=/var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/../scst/include SUBDIRS=/var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel modules
make[2]: Entering directory '/usr/src/linux-headers-4.4.0-62-generic'
  CC [M]  /var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/iscsi.o
  CC [M]  /var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/nthread.o
  CC [M]  /var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/config.o
  CC [M]  /var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/digest.o
  CC [M]  /var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/conn.o
  CC [M]  /var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/session.o
  CC [M]  /var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/target.o
  CC [M]  /var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/event.o
  CC [M]  /var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/param.o
  CC [M]  /var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/iscsit_transport.o
  LD [M]  /var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/iscsi-scst.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/iscsi-scst.mod.o
  LD [M]  /var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/iscsi-scst.ko
make[2]: Leaving directory '/usr/src/linux-headers-4.4.0-62-generic'
echo "mods:  INFINIBAND_ENABLED = true"
mods:  INFINIBAND_ENABLED = true
if true; then                                          \
  echo "  Building against in-tree InfiniBand kernel headers."; \
  make -C /lib/modules/4.4.0-62-generic/build SCST_INC_DIR=/var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/../scst/include SUBDIRS=/var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/isert-scst  \
  PRE_CFLAGS=""                                        \
  KBUILD_EXTRA_SYMBOLS=/var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/Module.symvers modules;                              \
fi
  Building against in-tree InfiniBand kernel headers.
make[2]: Entering directory '/usr/src/linux-headers-4.4.0-62-generic'
  CC [M]  /var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/isert-scst/isert.o
  CC [M]  /var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/isert-scst/isert_login.o
  CC [M]  /var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/isert-scst/iser_datamover.o
  CC [M]  /var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/isert-scst/iser_rdma.o
/var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/isert-scst/iser_rdma.c: In function ‘isert_device_create’:
/var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/isert-scst/iser_rdma.c:977:33: error: ‘struct ib_device’ has no member named ‘attrs’
  isert_dev->device_attr = ib_dev->attrs;
                                 ^
/var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/isert-scst/iser_rdma.c:1062:7: warning: passing argument 5 of ‘ib_create_cq’ makes pointer from integer without a cast [-Wint-conversion]
       cqe_num,
       ^
In file included from /var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/../scst/include/backport.h:29:0,
                 from /var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/../scst/include/scst_debug.h:41,
                 from /var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/isert-scst/isert_dbg.h:30,
                 from /var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/isert-scst/iser_rdma.c:43:
include/rdma/ib_verbs.h:2470:15: note: expected ‘const struct ib_cq_init_attr *’ but argument is of type ‘int’
 struct ib_cq *ib_create_cq(struct ib_device *device,
               ^
/var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/isert-scst/iser_rdma.c:1058:8: error: too many arguments to function ‘ib_create_cq’
   cq = ib_create_cq(ib_dev,
        ^
In file included from /var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/../scst/include/backport.h:29:0,
                 from /var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/../scst/include/scst_debug.h:41,
                 from /var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/isert-scst/isert_dbg.h:30,
                 from /var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/isert-scst/iser_rdma.c:43:
include/rdma/ib_verbs.h:2470:15: note: declared here
 struct ib_cq *ib_create_cq(struct ib_device *device,
               ^
/var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/isert-scst/iser_rdma.c: In function ‘isert_portal_create’:
/var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/isert-scst/iser_rdma.c:1798:8: warning: "RDMA_CREATE_ID_TAKES_NET_ARG" is not defined [-Wundef]
 #elif !RDMA_CREATE_ID_TAKES_NET_ARG
        ^
/var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/isert-scst/iser_rdma.c:1799:25: warning: passing argument 1 of ‘rdma_create_id’ from incompatible pointer type [-Wincompatible-pointer-types]
  cm_id = rdma_create_id(isert_cm_evt_handler, portal, RDMA_PS_TCP,
                         ^
In file included from /var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/isert-scst/iser.h:50:0,
                 from /var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/isert-scst/iser_rdma.c:44:
include/rdma/rdma_cm.h:172:20: note: expected ‘struct net *’ but argument is of type ‘int (*)(struct rdma_cm_id *, struct rdma_cm_event *)’
 struct rdma_cm_id *rdma_create_id(struct net *net,
                    ^
/var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/isert-scst/iser_rdma.c:1799:47: warning: passing argument 2 of ‘rdma_create_id’ from incompatible pointer type [-Wincompatible-pointer-types]
  cm_id = rdma_create_id(isert_cm_evt_handler, portal, RDMA_PS_TCP,
                                               ^
In file included from /var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/isert-scst/iser.h:50:0,
                 from /var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/isert-scst/iser_rdma.c:44:
include/rdma/rdma_cm.h:172:20: note: expected ‘rdma_cm_event_handler {aka int (*)(struct rdma_cm_id *, struct rdma_cm_event *)}’ but argument is of type ‘struct isert_portal *’
 struct rdma_cm_id *rdma_create_id(struct net *net,
                    ^
/var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/isert-scst/iser_rdma.c:1799:55: warning: passing argument 3 of ‘rdma_create_id’ makes pointer from integer without a cast [-Wint-conversion]
  cm_id = rdma_create_id(isert_cm_evt_handler, portal, RDMA_PS_TCP,
                                                       ^
In file included from /var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/isert-scst/iser.h:50:0,
                 from /var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/isert-scst/iser_rdma.c:44:
include/rdma/rdma_cm.h:172:20: note: expected ‘void *’ but argument is of type ‘int’
 struct rdma_cm_id *rdma_create_id(struct net *net,
                    ^
/var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/isert-scst/iser_rdma.c:1799:10: error: too few arguments to function ‘rdma_create_id’
  cm_id = rdma_create_id(isert_cm_evt_handler, portal, RDMA_PS_TCP,
          ^
In file included from /var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/isert-scst/iser.h:50:0,
                 from /var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/isert-scst/iser_rdma.c:44:
include/rdma/rdma_cm.h:172:20: note: declared here
 struct rdma_cm_id *rdma_create_id(struct net *net,
                    ^
scripts/Makefile.build:258: recipe for target '/var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/isert-scst/iser_rdma.o' failed
make[3]: *** [/var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/isert-scst/iser_rdma.o] Error 1
Makefile:1420: recipe for target '_module_/var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/isert-scst' failed
make[2]: *** [_module_/var/lib/dkms/scst/3.1.0.1/build/iscsi-scst/kernel/isert-scst] Error 2
make[2]: Leaving directory '/usr/src/linux-headers-4.4.0-62-generic'
Makefile:151: recipe for target 'mods' failed
make[1]: *** [mods] Error 2
make[1]: Leaving directory '/var/lib/dkms/scst/3.1.0.1/build/iscsi-scst'
Makefile:6: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by bvanassche** [comment]
How about using the SCST master branch instead of the SCST 3.1.x branch? The master branch builds fine against kernel 4.4.0 on my setup.

**Comment by mailinglists35** [comment]
it builds fine for me too (the manual `make` method), but I wanted to produce a deb package to be more organized and have less binaries in the system originated from non-deb sources. I think the issue is with the other repo that was supposed to produce a deb file and the author said does not have time to look into it :(

**Comment by mailinglists35** [comment]
oh, the debian folder contains code from 3.1
this really does not belong here. closing.
